name: dataverity-client

services:
  client:
    image: schweigenderflugel/dataverity:1.0.0-client
    container_name: dataverity-client
    hostname: localhost
    volumes:
      - ./env.js:/app/dist
    ports:
      - 5173:5173