---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: lawcase-eks
  region: sa-east-1
  tags:
    project: lawcase-project
nodeGroups:
  - name: worker-node
    instanceType: m5.large
    minSize: 1
    maxSize: 3
    desiredCapacity: 3
    volumeSize: 20
    volumeType: gp3
    ssh:
      allow: true
      publicKeyName: kube-ssh
    tags:
      Env: Dev
      k8s.io/cluster-autoscaler/enabled: 'true'
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      withAddonPolicies:
        autoScaler: true`