import type { StudentForm } from "@/interfaces/student-form";

export const defaultStudentData: StudentForm = {
  legajo: "",
  nombre: "",
  edad: 5,
  genero: "M",
  grado: 1,
  seccion: "A",
  asistencia_inicial: false,
  asistencia: 0,
  calificacion_matematica: 0,
  calificacion_lengua: 0,
  horas_clase_semanales: 0,
  motivacion: 1,
  habilidades_de_autorregulacion: 1,
  habilidades_interpersonales: 1,
  habilidades_intrapersonales: 1,
  conducta_riesgo: 1,
  libros_en_casa: false,
  internet_en_casa: false,
  distancia_escuela_km: 0,
  clima_escolar: 1,
  capacitacion_docente_anual_horas: 0,
  tenencia_director_anos: 0,
  adecuaciones_curriculares: false,
  tipo_neae: "Normal",
  violencia_familiar: false,
  enfermedad_grave_familiar: false,
  catastrofe_familiar: false,
  resiliencia_familiar: 1,
  conducta_riesgo_observada: false,
};
