apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace | default "frontend" }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.container.replicas | default 1 }} 
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - image: "{{ required "container.image is required" .Values.container.image }}:{{ required "container.tag is required" .Values.container.tag }}"
        name: {{ .Values.name | default "server" }}
        ports:
        - containerPort: {{ .Values.container.port | default 80 }}
        envFrom:
          - secretRef:
              name: dataverity-client-secrets
          - configMapRef:
              name: dataverity-client-configmap
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
